# Generated by Django 5.0.3 on 2024-04-09 12:21

import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='submenus',
            field=wagtail.fields.StreamField([('submenu_item', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.CharBlock())], blank=True))]),
        ),
    ]
