# Generated by Django 5.0.3 on 2024-04-11 12:33

import wagtail.blocks
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_menuitem_submenus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='is_dropdown',
            new_name='has_dropdown',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='submenus',
            field=wagtail.fields.StreamField([('submenu_item', wagtail.blocks.StructBlock([('label', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.CharBlock())]))], blank=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
