# Generated by Django 5.0.3 on 2024-04-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tagsnippet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TagSnippet',
        ),
    ]
