# Generated by Django 5.0.6 on 2024-06-28 11:52

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blogpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('video', wagtail.embeds.blocks.EmbedBlock()), ('gallery', wagtail.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('raw_html', wagtail.blocks.RawHTMLBlock())], blank=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('video', wagtail.embeds.blocks.EmbedBlock()), ('gallery', wagtail.blocks.StreamBlock([('image', wagtail.images.blocks.ImageChooserBlock())]))]),
        ),
    ]
